name: Rust

on:
  push:
    tags:        
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install wasm-pack from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: wasm-pack

    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./javascript
      run: wasm-pack build --target web
    - name: Run tests
      working-directory: ./javascript
      run: npm run test
